apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: books-api-stable
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: books-api.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: books-api-stable-service
            port:
              number: 80
