name: Release New Version

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag for the release of the application'
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Docker Login
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

    - name: Build Docker Image
      run: docker build . --file Dockerfile --tag juanwigg/go-book-api:${{ inputs.tag }}
    
    - name: Tag Docker Image
      run: docker tag juanwigg/go-book-api:${{ inputs.tag }} juanwigg/go-book-api:latest-stable
    
    - name: Docker Push
      run: |
        docker push ${{secrets.DOCKER_USER}}/go-book-api:${{ inputs.tag }}
        docker push ${{secrets.DOCKER_USER}}/go-book-api:latest-stable

    - uses: cschleiden/replace-tokens@v1
      with:
        files: '["kubernetes/rollout.yaml"]'
      env:
        IMAGE_TAG: ${{ inputs.tag }}
    
    - name: Configure Git Global values
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "Actions"

    - name: Stage changes
      run: git add .

    - name: Commit new file
      run: git commit -m "Rollout version ${{ inputs.tag }}"

    - name: Push changes
      run: git push origin release

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      with:
        tag_name: ${{ inputs.tag }
        release_name: Release ${{ inputs.tag }}
        draft: false
        prerelease: false
  